### PR TITLE
add missing print >> redirect

### PR DESCRIPTION
**Pull request by edquist**
discovered randomly while debugging #381

### CODE REVIEW

**Comment by matyasselmeci** [comment]
It should be a separate PR, but we should be using Python 3-compatible syntax in our code, i.e. `from __future__ import print_function` at the top and `print("blah blah blahp", file=sys.stderr)`...

**Comment by brianhlin** [comment]
@edquist could you cherry-pick this to the `stable` branch?

**Comment by edquist** [comment]
> It should be a separate PR, but we should be using Python 3-compatible syntax in our code, i.e. `from __future__ import print_function` at the top and `print("blah blah blahp", file=sys.stderr)`...

Python3 support is going to be a large overhaul, i think, for htcondor-ce.  It contains a large amount of python2-specific code all over the place - so i wasn't going to pretend to make a difference in this fix  ;)

**Comment by matyasselmeci** [comment]
Fair :)
It's pretty high on the prio list for RHEL 8 though, so I suspect we'll be getting to Python 3 fairly soon anyway.

**Pull request merged**
