### PR TITLE
Deploy immediately after tests for tags in htcondor/htcondor-ce

### PR DESCRIPTION
**Pull request by brianhlin**
I think this is how `deploy` is intended to be used. See this relevant build: https://travis-ci.org/brianhlin/htcondor-ce/jobs/566626525#L7209-L7210

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Looks like that's only gonna deploy the el7 rpms. Is that OK?

**Comment by brianhlin** [comment]
Oops, I misread the old deploy template. This should do it.

**Comment by matyasselmeci** [comment]
I don't see anything in the log message to the effect of 'deployment was skipped because this is a PR'. I'll try this out on my repo and see what happens.

**Comment by brianhlin** [comment]
Works on my repo for EL6: https://travis-ci.org/brianhlin/htcondor-ce/jobs/566634607#L7998-L7999

I think we don't see any messages because [PRs are skipped by default](https://docs.travis-ci.com/user/deployment/#pull-requests):

> Note that pull request builds skip the deployment step altogether.

**Comment by brianhlin** [comment]
It looks like this worked as expected, at least for EL7: https://travis-ci.org/htcondor/htcondor-ce/jobs/566671511#L6694

Not really sure what happened to the EL6 build, we didn't get the full logs: https://travis-ci.org/htcondor/htcondor-ce/jobs/566671510. There aren't any additional RPMs on the transfer host, though so success?

**Pull request merged**
