### PR TITLE
fix some glue-validator errors (now 0 err 0warn) and made some pylint…

### PR DESCRIPTION
**Pull request by sartiran**
…-recommended code formatting.

While setting up the new HTCondorCE at GRIF I had to modify this gip provider script provided by `htcondor-ce-bdii-3.3.0-1.el7.noarch` (which seems to be the master of this repo). Ive made just changes needed to make the bdii publication of the CE pass the glue-validator 

```
>> glue-validator -k -v3 -H localhost -p 2170 -b o=glue 
OK - errors 0, warnings 0, info 0 | errors=0;warnings=0;info=0
```

I've also made some minor code formatting to have a 9.5/10 pylint rating (10/10 would require some major reorganization of the code). But, if you wish I can re-do this PR without the formatting and with only the minimal changes needed to pass glue2 validation.

Regards,
Andrea SARITRANA (GRIF, IN2P3-LLR)

### CODE REVIEW

**Comment by brianhlin** [comment]
Hi @sartiran,

Thanks so much for the PR! I don't mind the pylint and glue validator fixes in the same PR but could you separate them out into different commits?

Also, is there packaging for the `glue-validator` tool? It would be a great addition to our CI tests!

Thanks,
Brian

**Comment by brianhlin** [comment]
Hi @sartiran have you had a chance to revisit this PR? I'm interested in cutting new versions of HTCondor-CE soon and would like for the new version to include your improvements!

**Comment by sartiran** [comment]
HI,
sorry for the late reply. I didn't get any mail notification about the PR messages. I'll split the commits ASAP.

Regards,
Andrea

**Comment by sartiran** [comment]
It is simpler if I close this PR and open a new one with the 2 commits.

**Pull request closed without merging**
