### PR TITLE
Glue validate

### PR DESCRIPTION
**Pull request by sartiran**
While setting up the new HTCondorCE at GRIF I had to modify this gip provider script provided by htcondor-ce-bdii-3.3.0-1.el7.noarch (which seems to be the master of this repo). Ive made just changes needed to make the bdii publication of the CE pass the glue-validator

>> glue-validator -k -v3 -H localhost -p 2170 -b o=glue 
OK - errors 0, warnings 0, info 0 | errors=0;warnings=0;info=0

I've also made some minor code formatting to have a 9.5/10 pylint rating (10/10 would require some major reorganization of the code). But, if you wish I can re-do this PR without the formatting and with 
only the minimal changes needed to pass glue2 validation.

As requested this PR was closed and reopened with split commits for the pylint and glue-validator parts

Regards,
Andrea SARITRANA (GRIF, IN2P3-LLR)

### CODE REVIEW

**Comment by sartiran** [comment]
BTW: when (if) this can be merged I'll be able to make another PR for publishing the GLUE2Benchmark parameters which are currently not published (and are somehow mandatory for the apel accounting).

**Comment by sartiran** [comment]
Hi Brian,
Thanks for the merging

The rpm for the glue validator is `glue-validator-2.0.25-0.el7.cern.noarch` in the UMD-4 release

**Comment by brianhlin** [comment]
Hi @sartiran,

You mentioned last week that you'd submit another PR for GLUE2Benchmark params (https://github.com/htcondor/htcondor-ce/pull/308#issuecomment-595230756). When do you expect to get around to that?

Thanks,
Brian

**Comment by sartiran** [comment]
Hi Brian,

the code is done and I'm making the PR asap. But I'm not sure this is well done and necessary (APEL actually needs the GLUE1 Bench attributes), so feel free to refuse or keep the PR on hold.

Regards,
Andrea

**Pull request merged**
