### PR TITLE
Make apelclient and ssmsend optional in apel cron script

### PR DESCRIPTION
**Pull request by drebatto**
See issue #431

### CODE REVIEW

**Review by brianhlin — COMMENTED** [review]
Hi @drebatto, thanks for the PR! This looks ok to me but I'd like @edquist's eyes on the bash bits first. Also, I'd be interested in a different configuration name: maybe something like `APEL_SEND_RECORDS` where we use `apelclient` + `ssmsend` when set to `True` (the default). I'd prefer it this way since there's a direct relationship with enabling/disabling a specific HTCondor-CE feature whereas `APEL_USE_PUBLISHER` makes it seem like the CE offers a "publisher" feature.

**Comment by drebatto** [comment]
Hi @brianhlin, it makes perfect sense. This is what I meant about getting the "CE-style" right :-)
I am going to make the change. By the way, I was wondering whether the bash function that wraps condor_config_val deserves a separate file, as it is used in three different scripts.

**Comment by brianhlin** [comment]
Hi @drebatto thanks for making the changes! We're doing some reorganizing of these scripts for the next release of HTCondor-CE 5 so we'll handle the function duplication on our end. That reminds me, though: would you be able to rebase these changes on `V5-branch` and re-submit the PR against that branch?

**Comment by brianhlin** [comment]
This has been resolved by #433, which resolves #431

**Pull request closed without merging**
