### PR TITLE
Pass on gwms distro requests to condor backends (SOFTWARE-2801)

### PR DESCRIPTION
**Pull request by brianhlin**
As requested by @jdost321

### CODE REVIEW

**Comment by djw8605** [comment]
Though, I'm open to a discussion.

**Comment by brianhlin** [comment]
We could add a config knob that controls whether or not we use this requirements expression.

**Comment by djw8605** [comment]
Really, I would like @bbockelm to weigh in.  I may be just blowing our use case out of proportion.

**Comment by bbockelm** [comment]
- What happens when a glidein requests `any`?
- What happens when there is a request for a non-RHEL site?  (i.e., Debian)?  I think we should probably whitelist known distros instead of blindly applying `substr`.
- Maybe have this requirement be an `eval_set` and be disabled if `WantDocker` is true?
- I would prefer to see the factory use the HTCondor nomenclature.

**Comment by brianhlin** [comment]
@bbockelm so you envision that the factories would submit pilots with something like the following?

```
requirements = "OpSysMajorVer =?= '6'"
```

**Comment by brianhlin** [comment]
I was going through old JIRA tickets and was reminded of this PR. If this is something we still want, I'm still unclear about what you meant here @bbockelm :

> I would prefer to see the factory use the HTCondor nomenclature.

**Comment by brianhlin** [comment]
Abandoning this

**Pull request closed without merging**
