### PR TITLE
Fix RPM upload GHA

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by brianhlin** [comment]
FWIW, we probably should just not use `/usr/sbin/init` as PID 1 in the container. I don't think it really matters what proc it is so we could probably just use `/bin/sh` but that's something that can be left for later

**Comment by matyasselmeci** [comment]
Why do you need --privileged?

**Comment by matyasselmeci** [comment]
You're not starting any services. Don't even specify a command to _docker run_; you'll get the default shell.

**Comment by timtheisen** [comment]
Otherwise the EL9 container does not stay running.

**Comment by matyasselmeci** [comment]
> Otherwise the EL9 container does not stay running.

What is the error message you get?

**Comment by timtheisen** [comment]
`Error response from daemon: Container 497247badd539902a91fab1a202f33dcb8b108303e8f8c1348c1ac0ede441b6d is not running`

**Pull request merged**
