### PR TITLE
Merge JR entry name check from V4-branch (HTCONDOR-406)

### PR DESCRIPTION
**Pull request by brianhlin**
Let's see if I did this right...

### CODE REVIEW

**Comment by JaimeFrey** [comment]
I scanned the other commits from V4-branch that come along for the ride. None result in changes in V5-branch, though perhaps one should: 1bc652ed95f.
It changes a `pwd` to "$PWD" in .github/workflows/build_rpms.yml to avoid creating an extra process. The equivalent code in build_and_test_rpms.yml in V5-branch has `pwd`.

**Review by JaimeFrey — APPROVED** [review]
LGTM!

**Comment by brianhlin** [comment]
Good catch @JaimeFrey! Do you think I should submit a separate PR with that commit included in the merge commit to maintain a reasonable `git merge-base`?

**Comment by JaimeFrey** [comment]
If you merge this PR, then the pwd commit will be merged as part of it. A separate PR of that commit won't do anything. And it looks like the relevant bit of code was added in different commits on the two branches, so git doesn't know they're related. A new commit on V5-branch (possibly in this PR) with the same change seems like the best option.

**Review by JaimeFrey — APPROVED** [review]

**Pull request merged**
